image: node:16

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker-runner
  before_script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
  script:
    - npm install --force
    - npm run generate
    - ls -all
  artifacts:
    paths:
      - dist/
  only:
    - main

deploy:
  image: python:3
  stage: deploy
  script:
    - ls -all
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync dist s3://3pl-dev.stallionexpress.xyz --region $AWS_DEFAULT_REGION
  only:
    - main
